customhost = "employee.cwhyo5rduj5d.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "fcuc1234"
customdb = "employee"
custombucket = "chinnnengzhi-employee"
customregion = "us-east-1"
